services:
  portfolio:
    image: kanakkhinge/portfolio:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kk-web
    ports:
      - "3454:80"
    restart: unless-stopped
